#! /bin/sh

bspc config border_width        2
bspc config window_gap          8
bspc config top_padding		30

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc config focused_border_color "#76D7CE"

bspc monitor -d I II III IV V VI VII VIII IX X

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Firefox desktop=^2
bspc rule -a mplayer2 floating=on

~/.config/bspwm/lemonbar/panel &
